name: Vinted → Discord (Node + Puppeteer)

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: |
          npm ci || npm i

      - name: Run
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          VINTED_PROFILE_URLS: ${{ secrets.VINTED_PROFILE_URLS }}
          ONLY_NEWER_HOURS: "24"
          MAX_ITEMS_PER_PROFILE: "20"
        run: |
          node index.js 

