name: vinted

on:
  schedule:
    - cron: "*/30 * * * *"   # a cada 30 min
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  run:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Recuperar o estado da última run (para não repetir posts)
      - name: Restore last vinted_state.json artifact (if any)
        shell: bash --noprofile --norc -e -o pipefail {0}
        env:
          GH_TOKEN: ${{ github.token }}
          REPO: ${{ github.repository }}
        run: |
          set -e
          echo "Procurar artefacto 'vinted-state' mais recente..."
          ART_ID=$(gh api repos/$REPO/actions/artifacts --paginate -q '.artifacts[] | select(.name=="vinted-state" and .expired==false) | .id' | head -n1 || true)
          if [ -n "$ART_ID" ]; then
            echo "Encontrado id=$ART_ID. A descarregar..."
            gh api -H "Accept: application/vnd.github+json" repos/$REPO/actions/artifacts/$ART_ID/zip > artifact.zip
            unzip -o artifact.zip || true
            rm -f artifact.zip
          else
            echo "Sem artefactos anteriores."
          fi

      - name: Ensure default state
        run: |
          if [ ! -f "vinted_state.json" ]; then
            echo '{"posted":{}, "lastPrune": 0}' > vinted_state.json
          fi
          echo "State file:"
          cat vinted_state.json

      - name: Install deps
        run: npm ci || npm i

      - name: Run scraper
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          # separa por vírgulas
          VINTED_PROFILE_URLS: ${{ vars.VINTED_PROFILE_URLS }}
          ONLY_NEWER_HOURS: ${{ vars.ONLY_NEWER_HOURS || 24 }}
          MAX_ITEMS_PER_PROFILE: ${{ vars.MAX_ITEMS_PER_PROFILE || 10 }}
          MAX_NEW_PER_PROFILE: ${{ vars.MAX_NEW_PER_PROFILE || 5 }}
          TEST_MODE: ${{ vars.TEST_MODE || 'false' }}
        run: node index.js

      - name: Upload vinted_state.json
        uses: actions/upload-artifact@v4
        with:
          name: vinted-state
          path: vinted_state.json
          retention-days: 60
